# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          touch todoist_variables.env
          echo todoist_url="https://todoist.com/auth/login" >> todoist_variables.env
          echo todoist_username=pablo.aversa@wizeline.com >> todoist_variables.env
          echo todoist_password= ${{ secrets.TODOIST_PASSWORD }} >> todoist_variables.env
          echo todoist_id_base_project= ${{ secrets.TODOIST_ID_BASE_PROJECT }} >> todoist_variables.env
          echo todoist_title_base_project= ${{ secrets.TODOIST_TITLE_BASE_PROJECT }} >> todoist_variables.env
          cat todoist_variables.env
      - run: ls
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run your tests
        run: npm run tests:smokeChromium
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
