# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-tests:
    runs-on: windows-latest # or macos-latest, windows-latest

  steps:
    — uses: actions/checkout@v2
    — uses: actions/setup-node@v2
      with:
        node-version: “16.x”
    — uses: microsoft/playwright-github-action@v1
    — name: Install Playwright Browsers
        run: npx playwright install — with-deps
    — name: Install dependencies and run tests
        run: npm install && npm run test:smokeChrome
    — uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
